services:
  api:
    build:
      context: ./api
    container_name: api_service
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/dbProjet
    volumes:
      - ./api:/app
      - /app/node_modules 
    depends_on:
      - mongo

  mobile:
    build:
      context: ./mobile
    container_name: mobile_service
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081" 
    depends_on:
      - api 
    stdin_open: true
    tty: true
    volumes:
      - ./mobile:/app
      - /app/node_modules 
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npx expo start --tunnel

  mongo:
    image: mongo:latest 
    container_name: mongo_db
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
